version: "3.9"
services:
  api: 
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
    ports:
      - "8000:80"
    container_name: "MenuPlannerAPI"
    networks:
      - menu_planner_backend_net
  mongo:
    container_name: "mongo"
    image: "mongo"
    restart: always
    ports:
      - "27018:27017"
    networks:
      - menu_planner_backend_net

networks:
  menu_planner_backend_net: