version: "3.9"
services:

  api: 
    build: 
      context: .
      dockerfile: ./API.MenuPlanner/Dockerfile
    image: michalkolarzyk/api_menu_planner
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - MENU_PLANNER_CONNECTION_STRING=mongodb://localhost:27017
    ports:
      - 8000:80
      - 8001:81
    container_name: "MenuPlannerAPI"
    networks:
      - menu_planner_test_net

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 5342:80
    environment:
      - ACCEPT_EULA=Y

  test:
    build:
      context: .
      dockerfile: ./Api.MenuPlannerTest/Dockerfile
    depends_on:
      - mongo
    environment:
      - MENU_PLANNER_CONNECTION_STRING=mongodb://mongo_test:27017
    networks:
      - menu_planner_test_net
      
  mongo:
    container_name: "mongo_test"
    image: "mongo"
    restart: always
    ports:
      - "27020:27017"
    networks:
      - menu_planner_test_net

networks:
  menu_planner_test_net: